// Run against `pnpm dev --host 127.0.0.1 --port 4173` with:
// playwright-cli -s=mimo-history run-code --filename test/audio-history-preview.probe.js
async (page) => {
  const history = page.locator('.xmimo-tts-history')
  const toggle = history.locator('.xmimo-ui-module-toggle')
  const count = history.locator('.xmimo-tts-history-count')
  if (await toggle.getAttribute('aria-expanded') !== 'true') await toggle.click()
  const clear = page.getByRole('button', { name: '清空历史', exact: true })
  if (await clear.count()) await clear.click()
  await page.getByRole('button', { name: '播放试听', exact: true }).click()
  await count.filter({ hasText: '1' }).waitFor()
  if (await toggle.getAttribute('aria-expanded') !== 'true') await toggle.click()
  const audio = history.locator('audio')
  await audio.evaluate(async (element) => { await element.play() })
  await audio.evaluate((element) => {
    if (element.readyState < 2) throw new Error('Saved audio did not decode')
    if (!(element.duration > 0)) throw new Error('Saved audio has no duration')
  })
  const downloaded = page.waitForEvent('download')
  await page.getByRole('link', { name: '下载', exact: true }).click()
  const download = await downloaded
  if (!download.suggestedFilename().endsWith('.wav')) throw new Error('Wrong download format')
  await download.saveAs('output/playwright/history-download.wav')
  await history.screenshot({ path: 'output/playwright/audio-history-desktop.png' })
  await page.reload()
  await count.filter({ hasText: '1' }).waitFor()
  await toggle.click()
  if (await audio.count() !== 1) throw new Error('History was not restored')
  await page.setViewportSize({ width: 390, height: 844 })
  await history.scrollIntoViewIfNeeded()
  await history.screenshot({ path: 'output/playwright/audio-history-mobile.png' })
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
  if (overflow) throw new Error('Mobile page overflows horizontally')
  await page.getByRole('button', { name: /^删除:/ }).click()
  await count.filter({ hasText: '0' }).waitFor()
  await page.reload()
  await count.filter({ hasText: '0' }).waitFor()
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.getByRole('combobox', { name: '语言', exact: true }).selectOption('en')
  await page.getByRole('combobox', { name: 'Theme', exact: true }).selectOption('dark')
  await page.getByRole('button', { name: 'Play preview', exact: true }).click()
  await count.filter({ hasText: '1' }).waitFor()
  await toggle.click()
  await history.screenshot({ path: 'output/playwright/audio-history-dark-en.png' })
  await page.getByRole('button', { name: 'Clear history', exact: true }).click()
  await count.filter({ hasText: '0' }).waitFor()
  console.log('PASS: preview synthesis, replay decoding, WAV download, reload, deletion, clear, mobile, and English dark theme')
}
