// Start: pnpm exec vite --config preview/vite.config.ts --host 127.0.0.1 --port 4173 --open false
// Run: playwright-cli -s=mimo-history run-code --filename test/audio-history-preview.probe.js
// Owns and replaces history only in the standalone preview browser origin.
async (page) => {
  const assert = (condition, message) => { if (!condition) throw new Error(message) }
  await page.setViewportSize({ width: 1280, height: 1000 })
  await page.addInitScript(() => {
    window.localStorage.removeItem('dsh-xiaomi-mimo-tts:minimal-mode')
    const NativeAudio = window.Audio
    window.__historyMedia = []
    window.Audio = class extends NativeAudio {
      constructor(...args) { super(...args); window.__historyMedia.push(this) }
    }
  })
  await page.goto('http://127.0.0.1:4173/')
  const entry = page.getByRole('button', { name: /^音频历史 ·/ })
  const history = page.getByRole('region', { name: '音频历史', exact: true })
  const footer = history.getByRole('contentinfo').or(history.locator('footer'))
  const open = async () => { await entry.click(); await history.waitFor() }
  const back = async () => { await history.getByRole('button', { name: '返回', exact: true }).click() }
  const clear = async () => {
    const button = history.getByRole('button', { name: '清空历史', exact: true })
    if (await button.count() && await button.isEnabled()) {
      await button.click()
      await history.getByRole('button', { name: '确认清空全部', exact: true }).click()
    }
  }
  await open()
  await clear()
  await back()
  await page.getByRole('textbox', { name: '试听文本', exact: true }).fill('历史试听 smoke test')
  await page.getByRole('button', { name: '播放试听', exact: true }).click()
  await entry.filter({ hasText: '1' }).waitFor()
  await open()
  await history.getByRole('button', { name: /^重听音频:/ }).click()
  await page.waitForFunction(() => window.__historyMedia.some((media) => media.duration > 0 && media.readyState >= 2))
  const downloaded = page.waitForEvent('download')
  await history.getByRole('button', { name: /^下载:/ }).click()
  const download = await downloaded
  assert(download.suggestedFilename().endsWith('.wav'), 'Preview history download should preserve WAV format')
  await download.saveAs('output/playwright/history-download.wav')
  await back()

  // Seed the existing IndexedDB schema with deterministic, decodable long audio.
  await page.evaluate(async () => {
    const size = 24000 * 16 * 2
    const bytes = new ArrayBuffer(44 + size)
    const wav = new DataView(bytes)
    const tag = (offset, value) => { for (let i = 0; i < value.length; i++) wav.setUint8(offset + i, value.charCodeAt(i)) }
    tag(0, 'RIFF'); wav.setUint32(4, 36 + size, true); tag(8, 'WAVE'); tag(12, 'fmt ')
    wav.setUint32(16, 16, true); wav.setUint16(20, 1, true); wav.setUint16(22, 1, true)
    wav.setUint32(24, 24000, true); wav.setUint32(28, 48000, true); wav.setUint16(32, 2, true); wav.setUint16(34, 16, true)
    tag(36, 'data'); wav.setUint32(40, size, true)
    const blob = new Blob([bytes], { type: 'audio/wav' })
    const db = await new Promise((resolve, reject) => { const request = indexedDB.open('dsh-xiaomi-tts-audio-history', 1); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) })
    await new Promise((resolve, reject) => {
      const transaction = db.transaction('audio', 'readwrite')
      const store = transaction.objectStore('audio')
      store.clear()
      for (let i = 0; i < 12; i++) store.put({
        id: `qa-${i}`, createdAt: Date.now() - i * 3600000, blob, format: 'wav',
        source: ['conversation', 'preview', 'service'][i % 3],
        text: i === 0 ? '早安，今天的安排已整理好。先完成最重要的一件事，再留一点时间给自己。 '.repeat(8) : i === 1 ? 'Hello MiMo — saved preview audio' : `音频记录 ${i + 1}：${['对话朗读', '设置试听', '服务播放'][i % 3]}`,
      })
      transaction.oncomplete = () => resolve()
      transaction.onerror = () => reject(transaction.error)
    })
    db.close()
  })
  await page.reload()
  await entry.filter({ hasText: '12' }).waitFor()
  const key = page.getByRole('textbox', { name: 'MiMo API Key', exact: true })
  await key.fill('draft-history-roundtrip')
  await open()
  assert(await page.getByRole('button', { name: '保存', exact: true }).count() === 0, 'History must not expose settings save')
  assert(await page.getByRole('button', { name: /^极简模式:/ }).count() === 0, 'History must not expose settings mode')
  const search = history.getByRole('searchbox', { name: '搜索音频摘要', exact: true })
  const source = history.getByRole('combobox', { name: '来源', exact: true })
  await search.fill('HELLO')
  assert(await history.getByRole('listitem').count() === 1, 'Summary search must ignore case')
  await source.selectOption('conversation')
  assert(await history.getByRole('listitem').count() === 0, 'Source and summary filters must compose')
  await history.getByRole('button', { name: '重置查找条件', exact: true }).click()
  assert(await history.getByRole('listitem').count() === 12, 'Reset filters restores every entry')
  const row = history.getByRole('listitem').first()
  const summary = row.getByRole('button', { name: /^展开或收起摘要:/ })
  await summary.click()
  assert(await summary.getAttribute('aria-expanded') === 'true', 'Summary expands')
  await summary.click()
  await row.getByRole('button', { name: /^重听音频:/ }).click()
  await footer.getByRole('button', { name: '暂停', exact: true }).waitFor()
  const slider = footer.getByRole('slider', { name: '播放进度', exact: true })
  await page.waitForFunction(() => document.querySelector('.xmimo-tts-history-player input[type=range]')?.max === '16')
  await footer.getByRole('button', { name: '暂停', exact: true }).click()
  await slider.focus()
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowRight')
  assert(Number(await slider.inputValue()) > 0, 'Keyboard seeking changes playback position')
  await slider.fill('4')
  assert(await footer.getByText('00:04 / 00:16', { exact: true }).isVisible(), 'Seeking updates the displayed playback time')
  // Force only the browser playback-policy boundary; keep the actual controller and UI.
  await page.evaluate(() => {
    window.__nativeHistoryPlay = HTMLMediaElement.prototype.play
    HTMLMediaElement.prototype.play = function () { return Promise.reject(new DOMException('Playback blocked for QA', 'NotAllowedError')) }
  })
  await footer.getByRole('button', { name: '播放', exact: true }).click()
  await footer.getByRole('button', { name: '重试播放', exact: true }).waitFor()
  assert(await footer.getByRole('status').isVisible(), 'Playback failure exposes its reason beside the retry control')
  await footer.screenshot({ path: 'output/playwright/audio-history-player-error.png' })
  await page.evaluate(() => { HTMLMediaElement.prototype.play = window.__nativeHistoryPlay; delete window.__nativeHistoryPlay })
  await footer.getByRole('button', { name: '重试播放', exact: true }).click()
  await footer.getByRole('button', { name: '暂停', exact: true }).waitFor()
  await page.waitForFunction(() => document.querySelector('.xmimo-tts-history-player input[type=range]')?.max === '16')
  await footer.getByRole('button', { name: '暂停', exact: true }).click()
  await slider.fill('4')
  await search.fill('HELLO')
  assert(await footer.getByRole('button', { name: '播放', exact: true }).count() === 1, 'Filtering preserves selected playback')
  await footer.getByRole('button', { name: '播放', exact: true }).click()
  await footer.getByRole('button', { name: '暂停', exact: true }).waitFor()
  await back()
  assert(await key.inputValue() === 'draft-history-roundtrip', 'Returning preserves an unsaved secret draft')
  assert(await page.getByRole('button', { name: '保存', exact: true }).isEnabled(), 'Draft remains unsaved after returning')
  assert(await entry.evaluate((button) => document.activeElement === button), 'Returning restores entry focus')
  assert(await page.evaluate(() => window.__historyMedia.every((media) => media.paused)), 'Leaving history stops media')
  await page.locator('.xmimo-tts-card-actions').screenshot({ path: 'output/playwright/audio-history-footer.png' })
  await page.getByRole('button', { name: /^极简模式:/ }).click()
  await open()
  assert(await history.evaluate((element) => !element.closest('.xmimo-tts-card-minimal')), 'History is independent of minimal settings')
  await history.getByRole('listitem').first().getByRole('button', { name: /^重听音频:/ }).click()
  await page.waitForFunction(() => document.querySelector('.xmimo-tts-history-player input[type=range]')?.max === '16')
  await footer.getByRole('button', { name: '暂停', exact: true }).waitFor()
  await footer.getByRole('button', { name: '暂停', exact: true }).click()
  await footer.getByRole('slider', { name: '播放进度', exact: true }).fill('4')
  await history.screenshot({ path: 'output/playwright/audio-history-desktop.png' })
  await footer.screenshot({ path: 'output/playwright/audio-history-player-desktop.png' })
  await history.locator('.xmimo-tts-history-results').evaluate((element) => { element.scrollTop = element.scrollHeight })
  assert(await footer.isVisible(), 'Playback controls stay visible while the list scrolls')
  await page.setViewportSize({ width: 390, height: 844 })
  await history.scrollIntoViewIfNeeded()
  await history.locator('.xmimo-tts-history-results').evaluate((element) => { element.scrollTop = 0 })
  await history.screenshot({ path: 'output/playwright/audio-history-mobile.png' })
  await footer.screenshot({ path: 'output/playwright/audio-history-player-mobile.png' })
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '390px page has no horizontal overflow')
  await page.setViewportSize({ width: 1280, height: 1000 })
  await page.evaluate(() => { document.documentElement.style.zoom = '2' })
  await history.scrollIntoViewIfNeeded()
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '200% zoom has no horizontal overflow')
  await history.screenshot({ path: 'output/playwright/audio-history-zoom.png' })
  await page.evaluate(() => { document.documentElement.style.zoom = '' })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await history.getByRole('searchbox').fill('早安')
  const active = history.getByRole('listitem').first()
  const deleteButton = await active.getByRole('button', { name: /^删除:/ }).elementHandle()
  const buttonCount = await active.getByRole('button').count()
  await deleteButton.click()
  assert(await history.getByRole('listitem').count() === 1, 'Deletion waits for confirmation')
  const confirmDelete = active.getByRole('button', { name: /^确认删除:/ })
  assert(await confirmDelete.evaluate((button, original) => button === original, deleteButton), 'Confirmation reuses the delete button')
  assert(await active.getByRole('button').count() === buttonCount, 'Confirmation adds no extra row controls')
  assert(await confirmDelete.evaluate((button) => {
    const channels = getComputedStyle(button).color.match(/[\d.]+/g).map(Number)
    return channels[0] > channels[1] && channels[0] > channels[2]
  }), 'Confirm delete uses the red danger color')
  await history.screenshot({ path: 'output/playwright/audio-history-confirm-delete-desktop.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await history.screenshot({ path: 'output/playwright/audio-history-confirm-delete-mobile.png' })
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Delete confirmation fits a narrow viewport')
  await page.setViewportSize({ width: 1280, height: 1000 })
  await confirmDelete.press('Escape')
  assert(await active.getByRole('button', { name: /^删除:/ }).isVisible(), 'Escape cancels deletion')
  await active.getByRole('button', { name: /^删除:/ }).click()
  await search.focus()
  assert(await active.getByRole('button', { name: /^删除:/ }).isVisible(), 'Moving focus cancels deletion')
  await active.getByRole('button', { name: /^删除:/ }).click()
  await confirmDelete.click()
  await page.waitForFunction(() => document.querySelector('.xmimo-tts-history-count')?.textContent?.includes('11'))
  assert(await slider.count() === 0, 'Deleting the selected audio resets playback')
  await clear()
  await page.reload()
  await entry.filter({ hasText: '0' }).waitFor()
  await open()
  assert(await history.getByRole('listitem').count() === 0, 'Clear removes filtered-out entries and persists')
  assert(await history.getByRole('searchbox').count() === 0 && await history.getByRole('combobox').count() === 0, 'An empty history omits lookup controls')
  assert(await history.getByRole('button', { name: '清空历史', exact: true }).count() === 0, 'An empty history omits the clear action')
  assert(await footer.count() === 0, 'An empty history omits playback controls')
  await back()
  await page.getByRole('combobox', { name: '语言', exact: true }).selectOption('en')
  await page.getByRole('combobox', { name: 'Theme', exact: true }).selectOption('dark')
  await page.getByRole('button', { name: 'Play preview', exact: true }).click()
  const englishEntry = page.getByRole('button', { name: /^Audio history ·/ })
  await englishEntry.filter({ hasText: '1' }).waitFor()
  await englishEntry.click()
  const englishHistory = page.getByRole('region', { name: 'Audio history', exact: true })
  await englishHistory.getByRole('button', { name: /^Listen again:/ }).click()
  await englishHistory.screenshot({ path: 'output/playwright/audio-history-dark-en.png' })
  await englishHistory.locator('footer').screenshot({ path: 'output/playwright/audio-history-player-dark-en.png' })
  await englishHistory.getByRole('button', { name: 'Back', exact: true }).click()
  const enabled = page.getByRole('checkbox', { name: /Whale maid is (on air|resting)/ })
  await enabled.focus()
  await page.keyboard.press('Space')
  assert(!await enabled.isChecked(), 'Keyboard can switch off TTS')
  await englishEntry.click()
  assert(await englishHistory.isVisible(), 'History remains reachable with TTS disabled')
  await englishHistory.getByRole('button', { name: 'Clear history', exact: true }).click()
  await englishHistory.getByRole('button', { name: 'Confirm clear all', exact: true }).click()
  const emptyImage = englishHistory.locator('.xmimo-tts-history-empty-whale')
  await emptyImage.waitFor()
  await page.waitForFunction(() => document.querySelector('.xmimo-tts-history-empty-whale')?.naturalWidth > 0)
  await englishHistory.screenshot({ path: 'output/playwright/audio-history-empty-dark.png' })
  await page.getByRole('combobox', { name: 'Theme', exact: true }).selectOption('light')
  await englishHistory.screenshot({ path: 'output/playwright/audio-history-empty-light.png' })
  await englishHistory.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByRole('button', { name: /^Minimal mode:/ }).click()
  await englishEntry.click()
  assert(await englishHistory.locator('.xmimo-tts-history-empty-whale').count() === 0, 'Minimal mode omits the empty-state illustration')
  assert(await englishHistory.getByRole('status').filter({ hasText: 'No generated audio' }).isVisible(), 'Minimal mode keeps the empty-state message')
  await englishHistory.screenshot({ path: 'output/playwright/audio-history-empty-minimal.png' })
  await englishHistory.getByRole('button', { name: 'Back', exact: true }).click()
  // Storage failure is a nondeterministic browser boundary; the actual history store falls back.
  await page.addInitScript(() => { Object.defineProperty(window, 'indexedDB', { configurable: true, get() { throw new Error('storage denied for QA') } }) })
  await page.reload()
  await page.getByRole('button', { name: '播放试听', exact: true }).click()
  await entry.filter({ hasText: '1' }).waitFor()
  await open()
  assert(await history.locator('[role=status]').filter({ hasText: '浏览器存储不可用' }).isVisible(), 'Temporary storage warning remains visible')
  await search.fill('no match')
  assert(await history.locator('[role=status]').filter({ hasText: '浏览器存储不可用' }).isVisible(), 'Filtering does not hide storage failure')
  await history.screenshot({ path: 'output/playwright/audio-history-memory.png' })
  console.log('PASS: preview synthesis, real WAV replay/download, reload, draft return/focus, search/source, summary, seek/pause, deletion/clear, disabled TTS, minimal entry, storage fallback, 390px, 200% zoom, English dark theme')
}
