import type {} from '@deepseek-ai/dsh-client-locale/client'

export const NS = 'xiaomi-mimo-tts'

export const zh = {
  "action.play": "朗读回复",
  "action.pause": "暂停朗读",
  "action.resume": "继续朗读",
  "action.loading": "正在生成语音",
  "action.cancel": "取消语音生成",
  "action.stop": "停止朗读",
  "action.localFallback": "本地语音",
  "action.retry": "重新生成语音",
  "error.noText": "没有可朗读的正文。",
  "error.request": "语音生成失败。",
  "error.play": "浏览器阻止了自动播放，请点击朗读按钮。",
  "error.localNotAllowed": "本地语音被拒绝了，请重试。",
  "error.localVoiceUnavailable": "当前浏览器音色不可用，请重新选择音色。",
  "error.localTimeout": "等待超时。",
  "error.localAudioDevice": "本地音频设备异常，请检查系统声音设置。",
  "error.localSynthesis": "本地语音合成失败，请重试。",
  "settings.title": "语音朗读 (Xiaomi MiMo)",
  "settings.description": "在对话中使用 Xiaomi MiMo TTS 生成并播放语音。",
  "settings.enabled": "语音播报",
  "settings.enabledOnLabel": "开麦啦",
  "settings.enabledOffLabel": "休息一会儿",
  "settings.enabledHint": "关闭后会隐藏语音设置并停止自动播报。",
  "settings.apiKey": "MiMo API Key",
  "settings.apiKeyStatus": "只有输入新值并保存时才会替换现有密钥。",
  "settings.apiKeyConfigured": "已配置",
  "settings.apiKeyMissing": "尚未配置 API Key，请先获取并设置密钥。",
  "settings.apiKeyUnsupported":
    "这个 API Key 似乎是错的，请检查（sk-/tp- 开头）。",
  "settings.getApiKey": "获取 API Key",
  "settings.apiKeyIdleCopy1": "我可以睁眼了吗？",
  "settings.apiKeyIdleCopy2": "密钥藏好了吗？",
  "settings.apiKeyIdleCopy3": "保存好就能开麦啦",
  "settings.apiKeyIdleCopy4": "好想偷看一眼…",
  "settings.apiKeyFocusCopy1": "好啦，我捂住眼睛",
  "settings.apiKeyFocusCopy2": "我什么都没看见",
  "settings.apiKeyFocusCopy3": "保密模式启动！",
  "settings.apiKeyFocusCopy4": "慢慢填，我替你保密",
  "settings.autoPlay": "自动播报",
  "settings.autoPlayOnLabel": "主动念给你听",
  "settings.autoPlayOffLabel": "等你叫我再念",
  "settings.autoPlayHint": "浏览器可能会拒绝自动播放。",
  "settings.detailedVoiceConfig": "调音台",
  "settings.voiceVolume": "语音音量",
  "settings.voiceRate": "播放语速",
  "settings.voiceRatePcmHint": "适用于全部语音；流式 PCM 倍速会同时改变音调。",
  "settings.readScope": "朗读范围",
  "settings.readScopeSmart": "智能选择",
  "settings.readScopeFull": "全文模式",
  "settings.readScopeFirstSegment": "首段模式",
  "settings.readScopeSmartHint":
    "自动播报短回复全部朗读、长回复智能截取首段，手动点击朗读全文。",
  "settings.readScopeFullHint": "自动播报和手动朗读都播放全文。",
  "settings.readScopeFirstSegmentHint": "保守朗读，自动播报和手动朗读都只播放首段。",
  "settings.summaryPresetModel": "预置音色",
  "settings.summaryVoiceDesignModel": "自定义音色",
  "settings.localSpeechAutoSummary": "MiMo 优先",
  "settings.stateOn": "已开启",
  "settings.stateOff": "已关闭",
  "settings.model": "模型选择",
  "settings.presetModel": "预置音色模型 (mimo-v2.5-tts)",
  "settings.voiceDesignModel": "自定义音色模型 (mimo-v2.5-tts-voicedesign)",
  "settings.presetModelShort": "预置音色(MiMo-TTS)",
  "settings.voiceDesignModelShort": "音色设计(MiMo-VoiceDesign)",
  "settings.localSpeechMode": "语音策略",
  "settings.localSpeechAuto": "MiMo 优先（默认）",
  "settings.localSpeechFirst": "本地优先",
  "settings.localSpeechDisabled": "关闭本地语音",
  "settings.localSpeechAutoHint": "优先使用 MiMo 音色，失败时使用本地语音。",
  "settings.localSpeechFirstHint":
    "优先使用浏览器本地语音朗读，失败时尝试使用 MiMo 音色。",
  "settings.localSpeechDisabledHint":
    "仅使用 MiMo 音色，失败时不会切换到本地语音。",
  "settings.localVoice": "本地音色",
  "settings.localVoiceLoading": "正在读取浏览器音色…",
  "settings.localVoiceUnavailable": "没有可用的浏览器音色",
  "settings.localVoiceOffline": "离线",
  "settings.localVoiceOnline": "在线",
  "settings.modelAutoPlayHintPreset": "预置音色自动使用低延迟流式播放。",
  "settings.modelAutoPlayHintVoiceDesign":
    "自定义音色仅支持在回复完成后自动播放。",
  "settings.voice": "内置音色",
  "settings.format": "音频格式",
  "settings.formatPcm": "PCM（流式播放）",
  "settings.formatMp3": "MP3（完整音频）",
  "settings.formatWav": "WAV（完整音频）",
  "settings.formatPcmHint": "边生成边播放，首个音频分片前失败时自动回退 MP3。",
  "settings.formatMp3Hint": "完整生成后播放，文件更小。",
  "settings.formatWavHint": "完整生成后播放，保留无损音频但文件更大。",
  "settings.voiceDesignPrompt": "音色设计",
  "settings.voiceDesignGenerate": "✨AI生成",
  "settings.voiceDesignGenerating": "生成中…",
  "settings.voiceDesignGenerateFailed": "AI生成失败，请重试。",
  "settings.voiceDesignAiCopy1": "我来帮你！",
  "settings.voiceDesignAiCopy2": "需要帮忙吗？",
  "settings.voiceDesignAiCopy3": "AI生成",
  "settings.voiceDesignAiCopy4": "我来帮你想想",
  "settings.voiceDesignAiSuccess": "生成完成！",
  "settings.customVoiceOption": "自定义",
  "settings.customVoiceSummary": "手动编写音色描述",
  "settings.voiceDesignPromptHint":
    "按“年龄段 + 性别、声音质感、语速节奏、情绪底色”描述声音本身；不写场景或动作。",
  "settings.voiceDesignPlaybackMode": "朗读方式",
  "settings.voiceDesignPlaybackComplete": "完整朗读",
  "settings.voiceDesignPlaybackSegmented": "分片朗读",
  "settings.voiceDesignPlaybackFirstSegment": "朗读首段",
  "settings.voiceDesignPlaybackCompleteHint":
    "整篇生成后播放，语调连续性更好。长文本会出现模型幻觉。",
  "settings.voiceDesignPlaybackSegmentedHint":
    "适合长文本，分段生成、更快播放。但会重新推导音色细节，语调连续性略差。",
  "settings.voiceDesignPlaybackFirstSegmentHint":
    "只生成并朗读首个分片，启动更快、消耗更低，适合快速试听或只听开头。",
  "settings.previewTitle": "演播厅",
  "settings.previewText": "试听文本",
  "settings.previewDefaultText":
    "你好呀，很高兴陪你一起探索声音的世界！这个声音听起来怎么样？",
  "settings.previewPlaceholder": "输入一段想试听的文字",
  "settings.previewPlay": "播放试听",
  "settings.previewStop": "停止试听",
  "settings.previewHint": "点我试听",
  "settings.previewLoading": "准备中…",
  "settings.previewPlaying": "播放中，再点停止",
  "settings.previewFailed": "试听失败，请检查设置",
  "settings.save": "保存",
  "settings.saving": "保存中…",
  "settings.saved": "已保存",
  "settings.unsaved": "未保存",
  "settings.overridden": "已覆盖",
  "settings.reset": "恢复默认",
  "settings.discard": "放弃修改",
  "settings.failed": "保存失败，请重试。",
  "settings.source": "✨查看源码",
  "settings.uninstall": "卸载",
  "settings.uninstalling": "卸载中…",
  "settings.uninstallQuestion": "确认卸载？",
  "settings.uninstallConfirm": "确认",
  "settings.uninstallCancel": "取消",
  "settings.uninstalled": "已卸载；重启DSH不再加载此插件。",
  "settings.uninstallFailed": "卸载失败，请重试或使用 DSH 命令行卸载。",
  "settings.updateAvailable": "🎉新版已发布",
  "settings.readOnly": "当前 DSH 设置为只读。",
  "settings.secretPlaceholder": "输入新的 Xiaomi MiMo API Key",
  "settings.expand": "展开设置",
  "settings.collapse": "收起设置",
  "settings.soundEffectsTitle": "音效库",
  "settings.soundEffectsEnabled": "启用音效",
  "settings.soundEffectsVolume": "音效音量",
  "settings.soundEffectsPack": "音效包",
  "settings.soundEffectsTask": "任务音效",
  "settings.soundEffectsClick": "点击音效",
  "settings.soundEffectsOn": "已开启",
  "settings.soundEffectsOff": "已关闭",
  "settings.soundEffectsOnLabel": "音效开启",
  "settings.soundEffectsOffLabel": "音效关闭",
  "settings.soundEffectsBubbleOn": "uisfx 已开启",
  "settings.soundEffectsBubbleOff": "uisfx 已关闭",
  "settings.soundEffectsTurnOn": "开启音效",
  "settings.soundEffectsTurnOff": "关闭音效",
  "settings.soundEffectsSynced": "任务 / 点击同步",
  "settings.soundEffectsPreviewLabel": "音效试听",
  "settings.soundEffectsPreview.start": "开始",
  "settings.soundEffectsPreview.complete": "完成",
  "settings.soundEffectsPreview.error": "失败",
  "settings.soundEffectsPreview.notification": "提醒",
  "settings.soundEffectsPreview.press": "点击",
  "settings.soundEffectsDescription":
    "为DSH接入uisfx语义化UI音效。在DSH中探索更多音效...",
  "settings.soundEffectsSupported":
    "🔔 开始 完成 成功 失败 提醒 点击 选择 开启 关闭 发送 打开 关闭面板 删除 停止 排队",
} as const;

export const en: Record<keyof typeof zh, string> = {
  "action.play": "Read aloud",
  "action.pause": "Pause speech",
  "action.resume": "Resume speech",
  "action.loading": "Generating speech",
  "action.cancel": "Cancel speech generation",
  "action.stop": "Stop speech",
  "action.localFallback": "Local speech",
  "action.retry": "Generate speech again",
  "error.noText": "This response has no readable body text.",
  "error.request": "Speech generation failed.",
  "error.play": "The browser blocked autoplay. Click Read aloud to play it.",
  "error.localNotAllowed":
    "The browser blocked local speech. Click Read aloud to try again.",
  "error.localVoiceUnavailable":
    "The selected browser voice is unavailable. Choose another voice.",
  "error.localTimeout":
    "Browser speech did not respond within 2 minutes, so this playback was stopped.",
  "error.localAudioDevice":
    "The local audio device reported an error. Check your system sound settings.",
  "error.localSynthesis": "Local speech synthesis failed. Please try again.",
  "settings.title": "Text To Speech (Xiaomi MiMo)",
  "settings.description":
    "Generate and play Xiaomi MiMo TTS audio from assistant message actions.",
  "settings.enabled": "Voice playback",
  "settings.enabledOnLabel": "Whale maid is on air",
  "settings.enabledOffLabel": "Whale maid is resting",
  "settings.enabledHint":
    "Disabling it hides voice settings and turns off automatic playback.",
  "settings.apiKey": "API Key",
  "settings.apiKeyStatus":
    "An existing key changes only when you save a new value.",
  "settings.apiKeyConfigured": "Configured",
  "settings.apiKeyMissing":
    "No API key is configured. Get and set an API key first.",
  "settings.apiKeyUnsupported":
    "This API key seems invalid. Check it and set it again (starting with sk- or tp-).",
  "settings.getApiKey": "Get API Key",
  "settings.apiKeyIdleCopy1": "Can I look now?",
  "settings.apiKeyIdleCopy2": "Is the key safely tucked away?",
  "settings.apiKeyIdleCopy3": "Save it, then we're on air!",
  "settings.apiKeyIdleCopy4": "I'll keep your key safe",
  "settings.apiKeyFocusCopy1": "Okay, eyes covered!",
  "settings.apiKeyFocusCopy2": "Don't worry, I can't see a thing",
  "settings.apiKeyFocusCopy3": "Privacy mode on!",
  "settings.apiKeyFocusCopy4": "Take your time—your secret is safe",
  "settings.autoPlay": "Automatic playback",
  "settings.autoPlayOnLabel": "I'll read it to you",
  "settings.autoPlayOffLabel": "Call me when you need me",
  "settings.autoPlayHint": "The browser may reject automatic playback.",
  "settings.detailedVoiceConfig": "Mixing Console",
  "settings.voiceVolume": "Voice volume",
  "settings.voiceRate": "Playback speed",
  "settings.voiceRatePcmHint": "Applies to all speech; streamed PCM changes pitch with playback speed.",
  "settings.readScope": "Read-aloud range",
  "settings.readScopeSmart": "Smart selection",
  "settings.readScopeFull": "Full mode",
  "settings.readScopeFirstSegment": "First-segment mode",
  "settings.readScopeSmartHint": "Automatic playback reads the opening segment; manual playback reads the full reply.",
  "settings.readScopeFullHint": "Both automatic and manual playback read the full reply.",
  "settings.readScopeFirstSegmentHint": "Both automatic and manual playback read only the opening segment.",
  "settings.summaryPresetModel": "Preset model",
  "settings.summaryVoiceDesignModel": "Custom voicedesign",
  "settings.localSpeechAutoSummary": "MiMo first",
  "settings.stateOn": "On",
  "settings.stateOff": "Off",
  "settings.model": "Voice source settings",
  "settings.presetModel": "Preset voices (mimo-v2.5-tts)",
  "settings.voiceDesignModel":
    "Custom voice design (mimo-v2.5-tts-voicedesign)",
  "settings.presetModelShort": "Preset voice (MiMo-TTS)",
  "settings.voiceDesignModelShort": "Voice design (MiMo-VoiceDesign)",
  "settings.localSpeechMode": "Speech strategy",
  "settings.localSpeechAuto": "MiMo first (default)",
  "settings.localSpeechFirst": "Local first",
  "settings.localSpeechDisabled": "Disable local speech",
  "settings.localSpeechAutoHint":
    "Uses the MiMo voice first and falls back to local speech if MiMo fails.",
  "settings.localSpeechFirstHint":
    "Uses browser-local speech first and tries the MiMo voice if local speech fails.",
  "settings.localSpeechDisabledHint":
    "Uses only the MiMo voice and never falls back to local speech.",
  "settings.localVoice": "Browser voice",
  "settings.localVoiceLoading": "Loading browser voices…",
  "settings.localVoiceUnavailable": "No browser voices available",
  "settings.localVoiceOffline": "Offline",
  "settings.localVoiceOnline": "Online",
  "settings.modelAutoPlayHintPreset":
    "Preset voices use low-latency streaming automatically.",
  "settings.modelAutoPlayHintVoiceDesign":
    "Custom voice design supports automatic playback only after the reply is complete.",
  "settings.voice": "Built-in voice",
  "settings.format": "Audio format",
  "settings.formatPcm": "PCM (streaming)",
  "settings.formatMp3": "MP3 (complete audio)",
  "settings.formatWav": "WAV (complete audio)",
  "settings.formatPcmHint":
    "Plays chunks as they arrive for a shorter wait; supports pause and resume. Falls back to MP3 if streaming fails before the first audio chunk.",
  "settings.formatMp3Hint":
    "Plays after the complete file is generated. Smaller file size; supports pause and resume.",
  "settings.formatWavHint":
    "Plays after the complete lossless file is generated. Larger file size; supports pause and resume.",
  "settings.voiceDesignPrompt": "Voice design",
  "settings.voiceDesignGenerate": "✨ Generate with AI",
  "settings.voiceDesignGenerating": "Generating…",
  "settings.voiceDesignGenerateFailed": "AI generation failed. Try again.",
  "settings.voiceDesignAiCopy1": "I can help!",
  "settings.voiceDesignAiCopy2": "Need a hand?",
  "settings.voiceDesignAiCopy3": "Generate with AI",
  "settings.voiceDesignAiCopy4": "Let me think",
  "settings.voiceDesignAiSuccess": "Generated!",
  "settings.customVoiceOption": "Custom",
  "settings.customVoiceSummary": "Write a custom voice description",
  "settings.voiceDesignPromptHint":
    "Describe the voice itself with age/gender, texture, pace, and emotional baseline; avoid scenes or actions.",
  "settings.voiceDesignPlaybackMode": "Read-aloud mode",
  "settings.voiceDesignPlaybackComplete": "Complete",
  "settings.voiceDesignPlaybackSegmented": "Segmented",
  "settings.voiceDesignPlaybackFirstSegment": "First segment",
  "settings.voiceDesignPlaybackCompleteHint":
    "Generates the entire reply before playback for better continuity.",
  "settings.voiceDesignPlaybackSegmentedHint":
    "Generates and plays semantic segments in order; better for long text and faster start.",
  "settings.voiceDesignPlaybackFirstSegmentHint":
    "Generates and plays only the first segment for a faster start and lower usage.",
  "settings.previewTitle": "Broadcast Studio",
  "settings.previewText": "Preview text",
  "settings.previewDefaultText":
    "Hi! I'm Whale Maid. It's lovely to explore the world of voices with you!",
  "settings.previewPlaceholder": "Enter some text to preview",
  "settings.previewPlay": "Play preview",
  "settings.previewStop": "Stop preview",
  "settings.previewHint": "Tap me to preview",
  "settings.previewLoading": "Getting ready…",
  "settings.previewPlaying": "Playing—tap again to stop",
  "settings.previewFailed": "Preview failed. Check settings",
  "settings.save": "Save",
  "settings.saving": "Saving…",
  "settings.saved": "Saved",
  "settings.unsaved": "Unsaved",
  "settings.overridden": "Overridden",
  "settings.reset": "Restore default",
  "settings.discard": "Discard changes",
  "settings.failed": "Save failed. Try again.",
  "settings.source": "✨ View source",
  "settings.uninstall": "Uninstall",
  "settings.uninstalling": "Uninstalling…",
  "settings.uninstallQuestion": "Confirm uninstall?",
  "settings.uninstallConfirm": "Confirm",
  "settings.uninstallCancel": "Cancel",
  "settings.uninstalled":
    "Uninstalled. DSH remains active and will not load the plugin on its next start.",
  "settings.uninstallFailed":
    "Uninstall failed. Try again or remove the plugin with the DSH CLI.",
  "settings.updateAvailable": "🎉 New release",
  "settings.readOnly": "DSH settings are read-only.",
  "settings.secretPlaceholder": "Enter a new Xiaomi MiMo API key",
  "settings.expand": "Expand settings",
  "settings.collapse": "Collapse settings",
  "settings.soundEffectsTitle": "Sound Effects",
  "settings.soundEffectsEnabled": "Enable sounds",
  "settings.soundEffectsVolume": "Volume",
  "settings.soundEffectsPack": "Sound pack",
  "settings.soundEffectsTask": "Task sounds",
  "settings.soundEffectsClick": "Click sounds",
  "settings.soundEffectsOn": "On",
  "settings.soundEffectsOff": "Off",
  "settings.soundEffectsOnLabel": "Magic sounds on",
  "settings.soundEffectsOffLabel": "Magic sounds off",
  "settings.soundEffectsBubbleOn": "UISFX enabled",
  "settings.soundEffectsBubbleOff": "UISFX disabled",
  "settings.soundEffectsTurnOn": "Turn sounds on",
  "settings.soundEffectsTurnOff": "Turn sounds off",
  "settings.soundEffectsSynced": "Task / click synced",
  "settings.soundEffectsPreviewLabel": "Sound previews",
  "settings.soundEffectsPreview.start": "Preview start",
  "settings.soundEffectsPreview.complete": "Preview complete",
  "settings.soundEffectsPreview.error": "Preview error",
  "settings.soundEffectsPreview.notification": "Preview notification",
  "settings.soundEffectsPreview.press": "Preview click",
  "settings.soundEffectsDescription": "Bringing semantic UISFX interface sounds to DSH. Explore more sounds in DSH...",
  "settings.soundEffectsSupported": "Supported sounds: Start, Complete, Success, Error, Notification, Press, Select, Toggle On, Toggle Off, Send, Open, Close, Delete, Stop, Queued",
};

export type LocaleKey = keyof typeof zh

export type Translate = (key: LocaleKey) => string

declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface LocaleNamespaceMap {
    'xiaomi-mimo-tts': LocaleKey
  }
}
