import type {} from '@deepseek-ai/dsh-client-locale/client'

export const NS = 'xiaomi-mimo-tts'

export const zh = {
  'action.play': '朗读回复',
  'action.pause': '暂停朗读',
  'action.resume': '继续朗读',
  'action.loading': '正在生成语音',
  'action.cancel': '取消语音生成',
  'action.stop': '停止朗读',
  'action.retry': '重新生成语音',
  'error.noText': '这条回复没有可朗读的正文。',
  'error.request': '语音生成失败。',
  'error.play': '浏览器阻止了自动播放，请点击朗读按钮。',
  'settings.title': '语音朗读 (Xiaomi MiMo)',
  'settings.description': '在助手回复操作栏中使用 Xiaomi MiMo TTS 生成并播放语音。',
  'settings.enabled': '显示朗读按钮',
  'settings.enabledHint': '关闭后不会在助手回复操作栏显示朗读按钮，也不会自动播报。',
  'settings.apiKey': 'API Key',
  'settings.apiKeyStatus': '只有输入新值并保存时才会替换现有密钥。',
  'settings.apiKeyConfigured': '已配置',
  'settings.apiKeyMissing': '尚未配置 API Key，请先获取并设置密钥。',
  'settings.apiKeyUnsupported': '这个 API Key 似乎是错的，请检查并重新设置（sk-/tp- 开头）。',
  'settings.getApiKey': '获取 API Key',
  'settings.autoPlay': '开启自动播报',
  'settings.autoPlayHint': '开启时会同步显示朗读按钮；浏览器也可能拒绝自动播放。',
  'settings.model': 'TTS 模型',
  'settings.presetModel': '预置音色模型 (mimo-v2.5-tts)',
  'settings.voiceDesignModel': '自定义音色模型 (mimo-v2.5-tts-voicedesign)',
  'settings.modelAutoPlayHintPreset': '预置音色模型支持实时流式播放。',
  'settings.modelAutoPlayHintVoiceDesign': '自定义音色仅支持在回复完成后自动播放。',
  'settings.voice': '内置音色',
  'settings.voiceDesignPrompt': '自定义音色描述',
  'settings.customVoiceOption': '自定义',
  'settings.customVoiceSummary': '手动编写音色描述',
  'settings.voiceDesignPromptHint': '按“年龄段 + 性别、声音质感、语速节奏、情绪底色”描述声音本身；不写场景或动作。',
  'settings.format': '音频格式',
  'settings.save': '保存',
  'settings.saving': '保存中…',
  'settings.saved': '已保存',
  'settings.unsaved': '未保存',
  'settings.overridden': '已覆盖',
  'settings.reset': '恢复默认',
  'settings.discard': '放弃修改',
  'settings.failed': '保存失败，请重试。',
  'settings.star': '点亮Star⭐',
  'settings.uninstall': '卸载此插件',
  'settings.uninstalling': '卸载中…',
  'settings.uninstallQuestion': '确认卸载？',
  'settings.uninstallConfirm': '确认',
  'settings.uninstallCancel': '取消',
  'settings.uninstalled': '已卸载，重启 DSH Web 后生效。',
  'settings.uninstallFailed': '卸载失败，请重试或使用 DSH 命令行卸载。',
  'settings.readOnly': '当前 DSH 设置为只读。',
  'settings.secretPlaceholder': '输入新的 Xiaomi MiMo API Key',
  'settings.expand': '展开设置',
  'settings.collapse': '收起设置',
} as const

export const en: Record<keyof typeof zh, string> = {
  'action.play': 'Read aloud',
  'action.pause': 'Pause speech',
  'action.resume': 'Resume speech',
  'action.loading': 'Generating speech',
  'action.cancel': 'Cancel speech generation',
  'action.stop': 'Stop speech',
  'action.retry': 'Generate speech again',
  'error.noText': 'This response has no readable body text.',
  'error.request': 'Speech generation failed.',
  'error.play': 'The browser blocked autoplay. Click Read aloud to play it.',
  'settings.title': 'Text To Speech (Xiaomi MiMo)',
  'settings.description': 'Generate and play Xiaomi MiMo TTS audio from assistant message actions.',
  'settings.enabled': 'Show read-aloud button',
  'settings.enabledHint': 'When disabled, the read-aloud button and automatic speech are both turned off.',
  'settings.apiKey': 'API Key',
  'settings.apiKeyStatus': 'An existing key changes only when you save a new value.',
  'settings.apiKeyConfigured': 'Configured',
  'settings.apiKeyMissing': 'No API key is configured. Get and set an API key first.',
  'settings.apiKeyUnsupported': 'This API key seems invalid. Check it and set it again (starting with sk- or tp-).',
  'settings.getApiKey': 'Get API Key',
  'settings.autoPlay': 'Enable automatic read-aloud',
  'settings.autoPlayHint': 'Enabling it also shows the read-aloud button; the browser may reject autoplay.',
  'settings.model': 'TTS model',
  'settings.presetModel': 'Preset voices (mimo-v2.5-tts)',
  'settings.voiceDesignModel': 'Custom voice design (mimo-v2.5-tts-voicedesign)',
  'settings.modelAutoPlayHintPreset': 'Preset voices support realtime streaming playback.',
  'settings.modelAutoPlayHintVoiceDesign': 'Custom voice design supports automatic playback only after the reply is complete.',
  'settings.voice': 'Built-in voice',
  'settings.voiceDesignPrompt': 'Custom voice description',
  'settings.customVoiceOption': 'Custom',
  'settings.customVoiceSummary': 'Write a custom voice description',
  'settings.voiceDesignPromptHint': 'Describe the voice itself with age/gender, texture, pace, and emotional baseline; avoid scenes or actions.',
  'settings.format': 'Audio format',
  'settings.save': 'Save',
  'settings.saving': 'Saving…',
  'settings.saved': 'Saved',
  'settings.unsaved': 'Unsaved',
  'settings.overridden': 'Overridden',
  'settings.reset': 'Restore default',
  'settings.discard': 'Discard changes',
  'settings.failed': 'Save failed. Try again.',
  'settings.star': 'Feedback or Star us ⭐',
  'settings.uninstall': 'Uninstall this plugin',
  'settings.uninstalling': 'Uninstalling…',
  'settings.uninstallQuestion': 'Confirm uninstall?',
  'settings.uninstallConfirm': 'Confirm',
  'settings.uninstallCancel': 'Cancel',
  'settings.uninstalled': 'Uninstalled. Restart DSH Web to apply the change.',
  'settings.uninstallFailed': 'Uninstall failed. Try again or remove the plugin with the DSH CLI.',
  'settings.readOnly': 'DSH settings are read-only.',
  'settings.secretPlaceholder': 'Enter a new Xiaomi MiMo API key',
  'settings.expand': 'Expand settings',
  'settings.collapse': 'Collapse settings',
}

export type LocaleKey = keyof typeof zh

export type Translate = (key: LocaleKey) => string

declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface LocaleNamespaceMap {
    'xiaomi-mimo-tts': LocaleKey
  }
}
