import type {} from '@deepseek-ai/dsh-client-locale/client'

export const NS = 'xiaomi-mimo-tts'

export const zh = {
  "action.play": "朗读回复",
  "action.pause": "暂停朗读",
  "action.resume": "继续朗读",
  "action.loading": "正在生成语音",
  "action.cancel": "取消语音生成",
  "action.stop": "停止朗读",
  "action.localFallback": "本地语音",
  "action.retry": "重新生成语音",
  "error.noText": "没有可朗读的正文。",
  "error.request": "语音生成失败。",
  "error.play": "自动播放失败。",
  "error.localNotAllowed": "本地语音被拒绝了，请重试。",
  "error.localVoiceUnavailable": "当前浏览器音色不可用，请重新选择音色。",
  "error.localTimeout": "等待超时。",
  "error.localAudioDevice": "音频设备异常，请检查系统声音设置。",
  "error.localSynthesis": "语音合成失败。",
  "settings.title": "语音朗读 (Xiaomi MiMo)",
  "settings.description": "在对话中使用 Xiaomi MiMo TTS 生成并播放语音。",
  "settings.minimalMode": "极简模式",
  "settings.minimalModeOn": "已开启",
  "settings.minimalModeOff": "已关闭",
  "settings.minimalModeShort": "极简UI",
  "settings.defaultModeShort": "默认UI",
  "settings.enabled": "语音播报",
  "settings.enabledOnLabel": "开麦啦",
  "settings.enabledOffLabel": "休息一会儿",
  "settings.enabledHint": "关闭后会隐藏语音设置并停止自动播报。",
  "settings.apiKey": "MiMo API Key",
  "settings.apiKeyStatus": "只有输入新值并保存时才会替换现有密钥。",
  "settings.apiKeyLoading": "正在读取 Host 中的密钥…",
  "settings.apiKeyMissing": "尚未保存 MiMo API Key。请先填写并保存，再进行 MiMo 试听。",
  "settings.apiKeyRecognized": "已保存 MiMo API Key，格式已识别；可通过演播厅确认实际连接。",
  "settings.apiKeyUnsupported": "密钥格式未识别，请检查是否以 sk- 或 tp- 开头。",
  "settings.apiKeyUnsupportedSaved": "已保存密钥的格式未识别；请填写新密钥或清除已保存的密钥。",
  "settings.apiKeyUnavailable": "暂时无法读取 Host 密钥状态，请检查连接后重试。",
  "settings.apiKeyPendingSave": "新密钥待保存；保存后才会用于 MiMo 试听。",
  "settings.apiKeyPendingClear": "保存后将清除已保存的密钥；如有基础配置，将恢复继承。",
  "settings.apiKeyClear": "清除",
  "settings.getApiKey": "获取 API Key",
  "settings.apiKeyIdleCopy1": "我可以睁眼了吗？",
  "settings.apiKeyIdleCopy2": "密钥藏好了吗？",
  "settings.apiKeyIdleCopy3": "保存好就能开麦啦",
  "settings.apiKeyIdleCopy4": "好想偷看一眼…",
  "settings.apiKeyFocusCopy1": "好啦，我捂住眼睛",
  "settings.apiKeyFocusCopy2": "我什么都没看见",
  "settings.apiKeyFocusCopy3": "保密模式启动！",
  "settings.apiKeyFocusCopy4": "慢慢填，我替你保密",
  "settings.autoPlay": "自动播报",
  "settings.autoPlayOnLabel": "主动念给你听",
  "settings.autoPlayOffLabel": "等你叫我再念",
  "settings.autoPlayHint": "浏览器可能会拒绝自动播放。",
  "settings.detailedVoiceConfig": "调音台",
  "settings.voiceVolume": "语音音量",
  "settings.voiceRate": "播放语速",
  "settings.voiceRatePcmHint": "适用于全部语音；流式 PCM 倍速会同时改变音调。",
  "settings.readScope": "朗读范围",
  "settings.readScopeSmart": "智能模式",
  "settings.readScopeFull": "全文模式",
  "settings.readScopeFirstSegment": "首段模式",
  "settings.readScopeSmartHint":
    "自动播报短回复全文；长回复截取首段，未读内容较多时随机补一句收尾语。手动朗读全文。",
  "settings.readScopeFullHint": "自动播报和手动朗读都播放全文。",
  "settings.readScopeFirstSegmentHint": "保守朗读，自动播报和手动朗读都只播放首段。",
  "settings.summaryPresetModel": "预置音色",
  "settings.summaryVoiceDesignModel": "自定义音色",
  "settings.mixerPresetCopy": "今天想用谁的声音？",
  "settings.mixerVoiceDesignCopy": "一起设计专属音色吧！",
  "settings.localSpeechAutoSummary": "MiMo 优先",
  "settings.stateOn": "已开启",
  "settings.stateOff": "已关闭",
  "settings.model": "模型选择",
  "settings.presetModel": "预置音色模型 (mimo-v2.5-tts)",
  "settings.voiceDesignModel": "自定义音色模型 (mimo-v2.5-tts-voicedesign)",
  "settings.presetModelShort": "预置音色(MiMo-TTS)",
  "settings.voiceDesignModelShort": "音色设计(MiMo-VoiceDesign)",
  "settings.localSpeechMode": "语音策略",
  "settings.localSpeechAuto": "MiMo 优先",
  "settings.localSpeechFirst": "本地优先",
  "settings.localSpeechDisabled": "关闭本地语音",
  "settings.localSpeechAutoHint": "优先使用 MiMo 音色，失败时使用本地语音。",
  "settings.localSpeechFirstHint":
    "优先使用浏览器本地语音朗读，失败时尝试使用 MiMo 音色。",
  "settings.localSpeechDisabledHint":
    "仅使用 MiMo 音色，失败时不会切换到本地语音。",
  "settings.localSpeechUnavailableHint": "当前浏览器没有可用的本地音色，仅可使用 MiMo 优先。",
  "settings.localVoice": "本地音色",
  "settings.localVoiceLoading": "正在读取浏览器音色…",
  "settings.localVoiceUnavailable": "没有可用的浏览器音色",
  "settings.localVoiceOffline": "离线",
  "settings.localVoiceOnline": "在线",
  "settings.modelAutoPlayHintPreset": "预置音色自动使用低延迟流式播放。",
  "settings.modelAutoPlayHintVoiceDesign":
    "自定义音色仅支持在回复完成后自动播放。",
  "settings.voice": "内置音色",
  "settings.format": "音频格式",
  "settings.formatPcm": "PCM（流式播放）",
  "settings.formatMp3": "MP3（完整音频）",
  "settings.formatWav": "WAV（完整音频）",
  "settings.formatPcmHint": "边生成边播放，首个音频分片前失败时自动回退 MP3。",
  "settings.formatMp3Hint": "完整生成后播放，文件更小。",
  "settings.formatWavHint": "完整生成后播放，保留无损音频但文件更大。",
  "settings.voiceDesignPrompt": "音色设计",
  "settings.customVoiceOption": "自定义",
  "settings.customVoiceSummary": "手动编写音色描述",
  "settings.voiceDesignPromptHint":
    "按“年龄段 + 性别、声音质感、语速节奏、情绪底色”描述声音本身；不写场景或动作。",
  "settings.voiceDesignPlaybackMode": "朗读方式",
  "settings.voiceDesignPlaybackComplete": "完整朗读",
  "settings.voiceDesignPlaybackSegmented": "分片朗读",
  "settings.voiceDesignPlaybackFirstSegment": "朗读首段",
  "settings.voiceDesignPlaybackCompleteHint":
    "整篇生成后播放，语调连续性更好。长文本会出现模型幻觉。",
  "settings.voiceDesignPlaybackSegmentedHint":
    "适合长文本，分段生成、更快播放。但会重新推导音色细节，语调连续性略差。",
  "settings.voiceDesignPlaybackFirstSegmentHint":
    "只生成并朗读首个分片，启动更快、消耗更低，适合快速试听或只听开头。",
  "settings.previewTitle": "演播厅",
  "settings.previewText": "试听文本",
  "settings.previewDefaultText":
    "你好呀，很高兴陪你一起探索声音的世界！这个声音听起来怎么样？",
  "settings.previewPlaceholder": "输入一段想试听的文字",
  "settings.previewPlay": "播放试听",
  "settings.previewPlayShort": "试听",
  "settings.previewStopShort": "停止",
  "settings.previewStop": "停止试听",
  "settings.previewHint": "保存密钥后可试听 MiMo",
  "settings.previewLoading": "准备中…",
  "settings.previewPlaying": "播放中，再点停止",
  "settings.previewLoadingMimo": "正在连接 MiMo…",
  "settings.previewLoadingLocal": "正在准备浏览器本地语音…",
  "settings.previewPlayingMimo": "MiMo 语音播放中，再点停止",
  "settings.previewPlayingLocal": "浏览器本地语音播放中，再点停止",
  "settings.previewCompletedMimo": "MiMo 试听完成",
  "settings.previewCompletedLocal": "本地语音试听完成",
  "settings.previewErrorApiKeyMissing": "尚未保存 MiMo API Key；请先保存，或启用本地语音。",
  "settings.previewErrorApiKeyRejected": "MiMo 拒绝了当前密钥，请检查或更换 API Key。",
  "settings.previewErrorRateLimited": "MiMo 请求过于频繁，请稍后再试。",
  "settings.previewErrorTimeout": "MiMo 响应超时，请检查网络后重试。",
  "settings.previewErrorLocalUnavailable": "当前浏览器没有可用的本地音色。",
  "settings.previewErrorAutoplay": "浏览器阻止了播放，请再次点击试听。",
  "settings.previewFailed": "试听失败，请检查设置和网络。",
  "settings.save": "保存",
  "settings.saving": "保存中…",
  "settings.saved": "已保存",
  "settings.unsaved": "未保存",
  "settings.overridden": "已覆盖",
  "settings.reset": "恢复默认",
  "settings.discard": "放弃修改",
  "settings.failed": "保存失败，请重试。",
  "settings.source": "🍬赏个Star",
  "settings.updateAvailable": "🎉新版已发布",
  "settings.readOnly": "当前 DSH 设置为只读。",
  "settings.secretPlaceholder": "输入新的 Xiaomi MiMo API Key",
  "settings.expand": "展开设置",
  "settings.collapse": "收起设置",
  "settings.soundEffectsTitle": "音效库",
  "settings.soundEffectsEnabled": "启用音效",
  "settings.soundEffectsVolume": "音效音量",
  "settings.soundEffectsPack": "音效包",
  "settings.soundEffectsTask": "任务音效",
  "settings.soundEffectsClick": "点击音效",
  "settings.soundEffectsOn": "已开启",
  "settings.soundEffectsOff": "已关闭",
  "settings.soundEffectsOnLabel": "音效开启",
  "settings.soundEffectsOffLabel": "音效关闭",
  "settings.soundEffectsBubbleOn": "已开启，点我切换",
  "settings.soundEffectsBubbleOff": "uisfx 已关闭",
  "settings.soundEffectsClickOnly": "仅开启点击音效",
  "settings.soundEffectsTaskOnly": "仅开启任务音效",
  "settings.soundEffectsCycle": "循环切换音效范围",
  "settings.soundEffectsTurnOn": "开启音效",
  "settings.soundEffectsTurnOff": "关闭音效",
  "settings.soundEffectsSynced": "任务 / 点击同步",
  "settings.soundEffectsPreviewLabel": "音效试听",
  "settings.soundEffectsPreview.start": "开始",
  "settings.soundEffectsPreview.complete": "完成",
  "settings.soundEffectsPreview.error": "失败",
  "settings.soundEffectsPreview.notification": "提醒",
  "settings.soundEffectsPreview.press": "点击",
  "settings.soundEffectsDescription":
    "为DSH接入uisfx语义化UI音效。在DSH中探索更多音效...",
  "settings.soundEffectsSupported":
    "🔔 开始 完成 成功 失败 提醒 点击 选择 开启 关闭 发送 打开 关闭面板 删除 停止 排队",
} as const;

export const en: Record<keyof typeof zh, string> = {
  "action.play": "Read aloud",
  "action.pause": "Pause speech",
  "action.resume": "Resume speech",
  "action.loading": "Generating speech",
  "action.cancel": "Cancel speech generation",
  "action.stop": "Stop speech",
  "action.localFallback": "Local speech",
  "action.retry": "Generate speech again",
  "error.noText": "This response has no readable body text.",
  "error.request": "Speech generation failed.",
  "error.play": "The browser blocked autoplay. Click Read aloud to play it.",
  "error.localNotAllowed":
    "The browser blocked local speech. Click Read aloud to try again.",
  "error.localVoiceUnavailable":
    "The selected browser voice is unavailable. Choose another voice.",
  "error.localTimeout":
    "Browser speech did not respond within 2 minutes, so this playback was stopped.",
  "error.localAudioDevice":
    "The local audio device reported an error. Check your system sound settings.",
  "error.localSynthesis": "Local speech synthesis failed. Please try again.",
  "settings.title": "Text To Speech (Xiaomi MiMo)",
  "settings.description":
    "Generate and play Xiaomi MiMo TTS audio from assistant message actions.",
  "settings.minimalMode": "Minimal mode",
  "settings.minimalModeOn": "On",
  "settings.minimalModeOff": "Off",
  "settings.minimalModeShort": "Minimal UI",
  "settings.defaultModeShort": "Default UI",
  "settings.enabled": "Voice playback",
  "settings.enabledOnLabel": "Whale maid is on air",
  "settings.enabledOffLabel": "Whale maid is resting",
  "settings.enabledHint":
    "Disabling it hides voice settings and turns off automatic playback.",
  "settings.apiKey": "API Key",
  "settings.apiKeyStatus":
    "An existing key changes only when you save a new value.",
  "settings.apiKeyLoading": "Reading the saved key status from the Host…",
  "settings.apiKeyMissing":
    "No MiMo API key is saved. Enter and save one before testing MiMo speech.",
  "settings.apiKeyRecognized":
    "A MiMo API key is saved and its format is recognized. Use Broadcast Studio to confirm the connection.",
  "settings.apiKeyUnsupported":
    "The key format is not recognized. Check that it starts with sk- or tp-.",
  "settings.apiKeyUnsupportedSaved":
    "The saved key format is not recognized. Enter a replacement or clear the saved key.",
  "settings.apiKeyUnavailable":
    "The Host key status is temporarily unavailable. Check the connection and try again.",
  "settings.apiKeyPendingSave":
    "This new key is waiting to be saved. MiMo previews will use it only after saving.",
  "settings.apiKeyPendingClear":
    "Saving will clear the saved key. A base key will be inherited if one is configured.",
  "settings.apiKeyClear": "Clear",
  "settings.getApiKey": "Get API Key",
  "settings.apiKeyIdleCopy1": "Can I look now?",
  "settings.apiKeyIdleCopy2": "Is the key safely tucked away?",
  "settings.apiKeyIdleCopy3": "Save it, then we're on air!",
  "settings.apiKeyIdleCopy4": "I'll keep your key safe",
  "settings.apiKeyFocusCopy1": "Okay, eyes covered!",
  "settings.apiKeyFocusCopy2": "Don't worry, I can't see a thing",
  "settings.apiKeyFocusCopy3": "Privacy mode on!",
  "settings.apiKeyFocusCopy4": "Take your time—your secret is safe",
  "settings.autoPlay": "Automatic playback",
  "settings.autoPlayOnLabel": "I'll read it to you",
  "settings.autoPlayOffLabel": "Call me when you need me",
  "settings.autoPlayHint": "The browser may reject automatic playback.",
  "settings.detailedVoiceConfig": "Mixing Console",
  "settings.voiceVolume": "Voice volume",
  "settings.voiceRate": "Playback speed",
  "settings.voiceRatePcmHint": "Applies to all speech; streamed PCM changes pitch with playback speed.",
  "settings.readScope": "Read-aloud range",
  "settings.readScopeSmart": "Smart mode",
  "settings.readScopeFull": "Full mode",
  "settings.readScopeFirstSegment": "First-segment mode",
  "settings.readScopeSmartHint": "Automatic playback reads short replies in full. For long replies, it reads the opening segment and may add a brief closing cue when substantial content remains. Manual playback reads the full reply.",
  "settings.readScopeFullHint": "Both automatic and manual playback read the full reply.",
  "settings.readScopeFirstSegmentHint": "Both automatic and manual playback read only the opening segment.",
  "settings.summaryPresetModel": "Preset model",
  "settings.summaryVoiceDesignModel": "Custom voicedesign",
  "settings.mixerPresetCopy": "A clear voice for every message.",
  "settings.mixerVoiceDesignCopy": "Design a voice that sounds like you.",
  "settings.localSpeechAutoSummary": "MiMo first",
  "settings.stateOn": "On",
  "settings.stateOff": "Off",
  "settings.model": "Voice source settings",
  "settings.presetModel": "Preset voices (mimo-v2.5-tts)",
  "settings.voiceDesignModel":
    "Custom voice design (mimo-v2.5-tts-voicedesign)",
  "settings.presetModelShort": "Preset voice (MiMo-TTS)",
  "settings.voiceDesignModelShort": "Voice design (MiMo-VoiceDesign)",
  "settings.localSpeechMode": "Speech strategy",
  "settings.localSpeechAuto": "MiMo first",
  "settings.localSpeechFirst": "Local first",
  "settings.localSpeechDisabled": "Disable local speech",
  "settings.localSpeechAutoHint":
    "Uses the MiMo voice first and falls back to local speech if MiMo fails.",
  "settings.localSpeechFirstHint":
    "Uses browser-local speech first and tries the MiMo voice if local speech fails.",
  "settings.localSpeechDisabledHint":
    "Uses only the MiMo voice and never falls back to local speech.",
  "settings.localSpeechUnavailableHint": "No browser voices are available, so only MiMo first can be used.",
  "settings.localVoice": "Browser voice",
  "settings.localVoiceLoading": "Loading browser voices…",
  "settings.localVoiceUnavailable": "No browser voices available",
  "settings.localVoiceOffline": "Offline",
  "settings.localVoiceOnline": "Online",
  "settings.modelAutoPlayHintPreset":
    "Preset voices use low-latency streaming automatically.",
  "settings.modelAutoPlayHintVoiceDesign":
    "Custom voice design supports automatic playback only after the reply is complete.",
  "settings.voice": "Built-in voice",
  "settings.format": "Audio format",
  "settings.formatPcm": "PCM (streaming)",
  "settings.formatMp3": "MP3 (complete audio)",
  "settings.formatWav": "WAV (complete audio)",
  "settings.formatPcmHint":
    "Plays chunks as they arrive for a shorter wait; supports pause and resume. Falls back to MP3 if streaming fails before the first audio chunk.",
  "settings.formatMp3Hint":
    "Plays after the complete file is generated. Smaller file size; supports pause and resume.",
  "settings.formatWavHint":
    "Plays after the complete lossless file is generated. Larger file size; supports pause and resume.",
  "settings.voiceDesignPrompt": "Voice design",
  "settings.customVoiceOption": "Custom",
  "settings.customVoiceSummary": "Write a custom voice description",
  "settings.voiceDesignPromptHint":
    "Describe the voice itself with age/gender, texture, pace, and emotional baseline; avoid scenes or actions.",
  "settings.voiceDesignPlaybackMode": "Read-aloud mode",
  "settings.voiceDesignPlaybackComplete": "Complete",
  "settings.voiceDesignPlaybackSegmented": "Segmented",
  "settings.voiceDesignPlaybackFirstSegment": "First segment",
  "settings.voiceDesignPlaybackCompleteHint":
    "Generates the entire reply before playback for better continuity.",
  "settings.voiceDesignPlaybackSegmentedHint":
    "Generates and plays semantic segments in order; better for long text and faster start.",
  "settings.voiceDesignPlaybackFirstSegmentHint":
    "Generates and plays only the first segment for a faster start and lower usage.",
  "settings.previewTitle": "Broadcast Studio",
  "settings.previewText": "Preview text",
  "settings.previewDefaultText":
    "Hi! I'm Whale Maid. It's lovely to explore the world of voices with you!",
  "settings.previewPlaceholder": "Enter some text to preview",
  "settings.previewPlay": "Play preview",
  "settings.previewPlayShort": "Preview",
  "settings.previewStopShort": "Stop",
  "settings.previewStop": "Stop preview",
  "settings.previewHint": "Save a key to test MiMo; browser speech may be used when no key is configured",
  "settings.previewLoading": "Getting ready…",
  "settings.previewPlaying": "Playing—tap again to stop",
  "settings.previewLoadingMimo": "Connecting to MiMo…",
  "settings.previewLoadingLocal": "Preparing browser-local speech…",
  "settings.previewPlayingMimo": "MiMo speech is playing—tap again to stop",
  "settings.previewPlayingLocal": "Browser-local speech is playing—tap again to stop",
  "settings.previewCompletedMimo": "MiMo preview complete",
  "settings.previewCompletedLocal": "Local-speech preview complete",
  "settings.previewErrorApiKeyMissing": "No MiMo API key is saved. Save one first, or enable local speech.",
  "settings.previewErrorApiKeyRejected": "MiMo rejected the saved key. Check or replace the API key.",
  "settings.previewErrorRateLimited": "MiMo is receiving too many requests. Try again shortly.",
  "settings.previewErrorTimeout": "MiMo timed out. Check the network and try again.",
  "settings.previewErrorLocalUnavailable": "This browser has no available local voice.",
  "settings.previewErrorAutoplay": "The browser blocked playback. Tap preview again.",
  "settings.previewFailed": "Preview failed. Check the settings and network.",
  "settings.save": "Save",
  "settings.saving": "Saving…",
  "settings.saved": "Saved",
  "settings.unsaved": "Unsaved",
  "settings.overridden": "Overridden",
  "settings.reset": "Restore default",
  "settings.discard": "Discard changes",
  "settings.failed": "Save failed. Try again.",
  "settings.source": "✨ View source",
  "settings.updateAvailable": "🎉 New release",
  "settings.readOnly": "DSH settings are read-only.",
  "settings.secretPlaceholder": "Enter a new Xiaomi MiMo API key",
  "settings.expand": "Expand settings",
  "settings.collapse": "Collapse settings",
  "settings.soundEffectsTitle": "Sound Effects",
  "settings.soundEffectsEnabled": "Enable sounds",
  "settings.soundEffectsVolume": "Volume",
  "settings.soundEffectsPack": "Sound pack",
  "settings.soundEffectsTask": "Task sounds",
  "settings.soundEffectsClick": "Click sounds",
  "settings.soundEffectsOn": "On",
  "settings.soundEffectsOff": "Off",
  "settings.soundEffectsOnLabel": "Magic sounds on",
  "settings.soundEffectsOffLabel": "Magic sounds off",
  "settings.soundEffectsBubbleOn": "Enabled, click to switch",
  "settings.soundEffectsBubbleOff": "UISFX disabled",
  "settings.soundEffectsClickOnly": "Click sounds only",
  "settings.soundEffectsTaskOnly": "Task sounds only",
  "settings.soundEffectsCycle": "Cycle sound scope",
  "settings.soundEffectsTurnOn": "Turn sounds on",
  "settings.soundEffectsTurnOff": "Turn sounds off",
  "settings.soundEffectsSynced": "Task / click synced",
  "settings.soundEffectsPreviewLabel": "Sound previews",
  "settings.soundEffectsPreview.start": "Preview start",
  "settings.soundEffectsPreview.complete": "Preview complete",
  "settings.soundEffectsPreview.error": "Preview error",
  "settings.soundEffectsPreview.notification": "Preview notification",
  "settings.soundEffectsPreview.press": "Preview click",
  "settings.soundEffectsDescription": "Bringing semantic UISFX interface sounds to DSH. Explore more sounds in DSH...",
  "settings.soundEffectsSupported": "Supported sounds: Start, Complete, Success, Error, Notification, Press, Select, Toggle On, Toggle Off, Send, Open, Close, Delete, Stop, Queued",
};

export type LocaleKey = keyof typeof zh

export type Translate = (key: LocaleKey) => string

declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface LocaleNamespaceMap {
    'xiaomi-mimo-tts': LocaleKey
  }
}
